# -*- coding: utf-8 -*-
"""
qc_visualize_day_snr_los.py

For one specified date folder of preprocessed npz files (generated by
pre_process_batch_snr_qc.py), visualize:
1. peak-SNR time-height curtains
2. QC timeline
3. LOS radial-velocity anomaly diagnostics

Outputs are saved under OUTPUT_ROOT / <date_folder_name>.

Notes
-----
- The script assumes the npz files contain the fields written by
  pre_process_batch_snr_qc.py.
- For LOS anomaly analysis, the first 27 columns of los_velo are used,
  corresponding to P-channel gates 4~30, consistent with range_m.
"""

from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# ======================== User settings ========================
PREPROCESSED_DATE_DIR = Path(r"E:\测风组实验数据\气溶胶反演\预处理_SNR_QC\2026_04_19")
OUTPUT_ROOT = Path(r"E:\测风组实验数据\气溶胶反演\预处理_SNR_QC\qc_diagnostics")

# SNR curtain options
USE_COMBINED_SNR = True  # if True, use max(P,S); otherwise also save P and S separately
SNR_VMIN_DB = 0.0
SNR_VMAX_DB = 20.0

# Gap thresholds for blank display
TIME_GAP_THRESHOLD_SECONDS = 30.0

# LOS anomaly diagnosis
N_AZIMUTH_PER_VAD = 16
LOS_LOW_GATE_COUNT = 10      # use first 10 low gates among the 27 aligned P gates
LOS_ANOMALY_Z_THRESHOLD = 3.5
EPS = 1e-12

# plotting style
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams["font.size"] = 12
plt.rcParams["axes.unicode_minus"] = False


# ======================== Utilities ========================
def parse_date_like_to_date(value):
    s = str(value).strip()
    s = s.replace("_", "-").replace("/", "-").replace(".", "-")
    if s.isdigit() and len(s) == 8:
        dt = pd.to_datetime(s, format="%Y%m%d", errors="coerce")
    else:
        dt = pd.to_datetime(s, errors="coerce")
    if pd.isna(dt):
        raise ValueError(f"Cannot parse date: {value}")
    return dt.date()


def get_date_from_folder_name(folder: str | Path):
    return parse_date_like_to_date(Path(folder).name)


def utc_seconds_to_local_datetime_index(utc_seconds: np.ndarray) -> pd.DatetimeIndex:
    utc_seconds = np.asarray(utc_seconds, dtype=np.float64)
    dt_utc = pd.to_datetime(utc_seconds, unit="s", utc=True)
    return dt_utc.tz_convert("Asia/Shanghai")


def datetime_index_to_plot_num(dt_index: pd.DatetimeIndex) -> np.ndarray:
    dt_naive = dt_index.tz_localize(None)
    return mdates.date2num(dt_naive.to_pydatetime())


def auto_vmax(data_2d: np.ndarray):
    valid = np.asarray(data_2d, dtype=np.float64)
    valid = valid[np.isfinite(valid)]
    if valid.size == 0:
        return 1.0
    vmax = np.nanpercentile(valid, 99.0)
    if not np.isfinite(vmax) or vmax <= 0:
        vmax = np.nanmax(valid)
    if not np.isfinite(vmax) or vmax <= 0:
        vmax = 1.0
    return vmax


def insert_blank_columns_for_gaps(
    time_local: pd.DatetimeIndex,
    field_2d: np.ndarray,
    gap_threshold_seconds: float,
):
    time_local = pd.DatetimeIndex(time_local)
    field_2d = np.asarray(field_2d, dtype=np.float64)

    if field_2d.ndim != 2:
        raise ValueError("field_2d must be 2D")
    if field_2d.shape[0] != len(time_local):
        raise ValueError("time_local length must match field_2d.shape[0]")

    if len(time_local) <= 1:
        return time_local, field_2d

    out_times = []
    out_fields = []
    nan_profile = np.full((field_2d.shape[1],), np.nan, dtype=np.float64)

    for i in range(len(time_local) - 1):
        t0 = time_local[i]
        t1 = time_local[i + 1]
        out_times.append(t0)
        out_fields.append(field_2d[i])

        gap_seconds = (t1 - t0).total_seconds()
        if gap_seconds > gap_threshold_seconds:
            left_blank_time = t0 + pd.Timedelta(seconds=1)
            right_blank_time = t1 - pd.Timedelta(seconds=1)
            if right_blank_time <= left_blank_time:
                mid_blank_time = t0 + (t1 - t0) / 2
                out_times.append(mid_blank_time)
                out_fields.append(nan_profile.copy())
            else:
                out_times.append(left_blank_time)
                out_fields.append(nan_profile.copy())
                out_times.append(right_blank_time)
                out_fields.append(nan_profile.copy())

    out_times.append(time_local[-1])
    out_fields.append(field_2d[-1])

    return pd.DatetimeIndex(out_times), np.vstack(out_fields)


def make_masked_cmap(base_cmap: str = "viridis"):
    cmap = plt.get_cmap(base_cmap).copy()
    cmap.set_bad(color="white", alpha=0.0)
    return cmap


# ======================== Readers ========================
def load_one_npz(npz_path: str | Path):
    npz_path = Path(npz_path)
    with np.load(npz_path, allow_pickle=False) as d:
        out = {
            "timestamp": np.asarray(d["timestamp"], dtype=np.float64).reshape(-1),
            "azimuth": np.asarray(d["azimuth"], dtype=np.float64).reshape(-1),
            "range_m": np.asarray(d["range_m"], dtype=np.float64).reshape(-1),
            "los_velo": np.asarray(d["los_velo"], dtype=np.float64),
            "p_peak_snr_db": np.asarray(d["p_peak_snr_db"], dtype=np.float64),
            "s_peak_snr_db": np.asarray(d["s_peak_snr_db"], dtype=np.float64),
            "combined_gate_valid": np.asarray(d["combined_gate_valid"], dtype=bool),
            "low_gate_valid_count": np.asarray(d["low_gate_valid_count"], dtype=np.int32),
            "profile_valid": np.asarray(d["profile_valid"], dtype=bool),
            "source_h5_path": str(d["source_h5_path"]).strip(),
        }
    out["time_local"] = utc_seconds_to_local_datetime_index(out["timestamp"])
    out["npz_path"] = str(npz_path)
    return out


def collect_one_day(date_dir: str | Path):
    date_dir = Path(date_dir)
    npz_files = sorted(date_dir.glob("*_preprocessed.npz"))
    if len(npz_files) == 0:
        raise FileNotFoundError(f"No *_preprocessed.npz found in {date_dir}")

    ts_all, az_all, los_all = [], [], []
    p_snr_all, s_snr_all = [], []
    gate_valid_all, low_valid_all, profile_valid_all = [], [], []
    source_npz_all, source_h5_all = [], []
    range_ref = None

    for npz_path in npz_files:
        d = load_one_npz(npz_path)
        if range_ref is None:
            range_ref = d["range_m"]
        else:
            if not np.allclose(range_ref, d["range_m"], atol=1e-6, rtol=0):
                raise ValueError(f"range_m mismatch in {npz_path}")

        n = len(d["timestamp"])
        ts_all.append(d["timestamp"])
        az_all.append(d["azimuth"])
        los_all.append(d["los_velo"])
        p_snr_all.append(d["p_peak_snr_db"])
        s_snr_all.append(d["s_peak_snr_db"])
        gate_valid_all.append(d["combined_gate_valid"])
        low_valid_all.append(d["low_gate_valid_count"])
        profile_valid_all.append(d["profile_valid"])
        source_npz_all.extend([str(npz_path)] * n)
        source_h5_all.extend([d["source_h5_path"]] * n)

    ts_all = np.concatenate(ts_all, axis=0)
    az_all = np.concatenate(az_all, axis=0)
    los_all = np.concatenate(los_all, axis=0)
    p_snr_all = np.concatenate(p_snr_all, axis=0)
    s_snr_all = np.concatenate(s_snr_all, axis=0)
    gate_valid_all = np.concatenate(gate_valid_all, axis=0)
    low_valid_all = np.concatenate(low_valid_all, axis=0)
    profile_valid_all = np.concatenate(profile_valid_all, axis=0)
    source_npz_all = np.asarray(source_npz_all)
    source_h5_all = np.asarray(source_h5_all)

    sort_idx = np.argsort(ts_all)
    ts_all = ts_all[sort_idx]
    az_all = az_all[sort_idx]
    los_all = los_all[sort_idx]
    p_snr_all = p_snr_all[sort_idx]
    s_snr_all = s_snr_all[sort_idx]
    gate_valid_all = gate_valid_all[sort_idx]
    low_valid_all = low_valid_all[sort_idx]
    profile_valid_all = profile_valid_all[sort_idx]
    source_npz_all = source_npz_all[sort_idx]
    source_h5_all = source_h5_all[sort_idx]

    time_local = utc_seconds_to_local_datetime_index(ts_all)
    combined_snr_db = np.nanmax(np.stack([p_snr_all, s_snr_all], axis=0), axis=0)

    # los_velo: use first 27 columns to match P-channel gates 4~30 and range_m
    los_aligned = los_all[:, :len(range_ref)]

    return {
        "range_m": range_ref,
        "timestamp_utc_s": ts_all,
        "time_local": time_local,
        "azimuth_deg": az_all,
        "los_velo_aligned": los_aligned,
        "p_peak_snr_db": p_snr_all,
        "s_peak_snr_db": s_snr_all,
        "combined_peak_snr_db": combined_snr_db,
        "combined_gate_valid": gate_valid_all,
        "low_gate_valid_count": low_valid_all,
        "profile_valid": profile_valid_all,
        "source_npz_path": source_npz_all,
        "source_h5_path": source_h5_all,
    }


# ======================== LOS anomaly diagnostics ========================
def fit_vad_sinusoid(azimuth_deg: np.ndarray, vr: np.ndarray):
    """
    Fit vr = a*sin(az) + b*cos(az) + c by least squares.
    This is sufficient for anomaly detection and does not require
    explicit wind-coordinate convention.
    """
    az = np.deg2rad(np.asarray(azimuth_deg, dtype=np.float64))
    vr = np.asarray(vr, dtype=np.float64)
    X = np.column_stack([np.sin(az), np.cos(az), np.ones_like(az)])
    coef, _, _, _ = np.linalg.lstsq(X, vr, rcond=None)
    fit = X @ coef
    resid = vr - fit
    return coef, fit, resid


def robust_zscore(x: np.ndarray, eps: float = EPS):
    x = np.asarray(x, dtype=np.float64)
    med = np.nanmedian(x)
    mad = np.nanmedian(np.abs(x - med))
    scale = 1.4826 * mad
    if not np.isfinite(scale) or scale < eps:
        scale = np.nanstd(x)
    if not np.isfinite(scale) or scale < eps:
        scale = 1.0
    z = (x - med) / scale
    return z, med, scale


def compute_los_radial_anomaly_scores(day_data: dict):
    """
    Compute one anomaly score per radial using file-internal 16-radial groups.
    The score is based on low-gate mean LOS velocity residual from a fitted sinusoid.
    """
    time_local = day_data["time_local"]
    ts = day_data["timestamp_utc_s"]
    az = day_data["azimuth_deg"]
    los_aligned = day_data["los_velo_aligned"]
    source_npz = day_data["source_npz_path"]

    n_radial = len(ts)
    score = np.full((n_radial,), np.nan, dtype=np.float64)
    resid = np.full((n_radial,), np.nan, dtype=np.float64)
    low_mean = np.nanmean(los_aligned[:, :LOS_LOW_GATE_COUNT], axis=1)
    flagged = np.zeros((n_radial,), dtype=bool)

    unique_files = pd.unique(source_npz)

    for fp in unique_files:
        idx = np.where(source_npz == fp)[0]
        if idx.size == 0:
            continue

        # within file, keep time order
        idx = idx[np.argsort(ts[idx])]
        n_cycle = idx.size // N_AZIMUTH_PER_VAD
        n_used = n_cycle * N_AZIMUTH_PER_VAD
        if n_cycle == 0:
            continue

        idx_used = idx[:n_used]
        idx_groups = idx_used.reshape(n_cycle, N_AZIMUTH_PER_VAD)

        for g in range(n_cycle):
            ii = idx_groups[g]
            vr_group = low_mean[ii]
            az_group = az[ii]
            _, fit_group, resid_group = fit_vad_sinusoid(az_group, vr_group)
            z, _, _ = robust_zscore(resid_group)
            score[ii] = np.abs(z)
            resid[ii] = resid_group
            flagged[ii] = np.abs(z) >= LOS_ANOMALY_Z_THRESHOLD

    return {
        "los_low_gate_mean": low_mean,
        "los_residual_low_gate_mean": resid,
        "los_anomaly_score": score,
        "los_anomaly_flag": flagged,
    }


# ======================== Plotting ========================
def plot_time_height_field(
    time_local: pd.DatetimeIndex,
    height_km: np.ndarray,
    field_2d: np.ndarray,
    out_png: str | Path,
    title: str,
    cbar_label: str,
    vmin=None,
    vmax=None,
    gap_threshold_seconds: float = TIME_GAP_THRESHOLD_SECONDS,
    cmap_name: str = "viridis",
):
    time_plot, field_plot = insert_blank_columns_for_gaps(
        time_local=time_local,
        field_2d=field_2d,
        gap_threshold_seconds=gap_threshold_seconds,
    )
    t_num = datetime_index_to_plot_num(time_plot)
    field_masked = np.ma.masked_invalid(field_plot.T)
    cmap = make_masked_cmap(cmap_name)

    if vmax is None:
        vmax = auto_vmax(field_2d)

    plt.figure(figsize=(12, 6))
    mesh = plt.pcolormesh(
        t_num, height_km, field_masked, shading="auto", cmap=cmap, vmin=vmin, vmax=vmax
    )
    plt.colorbar(mesh, label=cbar_label)
    plt.xlabel("Local time (UTC+8)")
    plt.ylabel("Height (km)")
    plt.title(title)
    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    plt.xticks(rotation=30)
    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close()


def plot_profile_valid_timeline(time_local, profile_valid, low_gate_valid_count, out_png):
    t_num = datetime_index_to_plot_num(time_local)
    y = np.where(profile_valid, 1.0, 0.0)

    fig, ax1 = plt.subplots(figsize=(12, 3.8))
    ax1.step(t_num, y, where="mid", linewidth=1.3, label="profile_valid")
    ax1.set_ylim(-0.1, 1.1)
    ax1.set_yticks([0, 1])
    ax1.set_yticklabels(["invalid", "valid"])
    ax1.set_xlabel("Local time (UTC+8)")
    ax1.set_ylabel("Profile QC")

    ax2 = ax1.twinx()
    ax2.plot(t_num, low_gate_valid_count, linewidth=1.0, alpha=0.75, label="low_gate_valid_count")
    ax2.set_ylabel("Valid low gates")

    ax1.set_title("Profile-level QC timeline")
    ax1.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax1.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    plt.xticks(rotation=30)
    fig.tight_layout()
    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_los_anomaly_timeline(time_local, los_low_gate_mean, score, flag, out_png):
    t_num = datetime_index_to_plot_num(time_local)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True, constrained_layout=True)

    ax1.plot(t_num, los_low_gate_mean, linewidth=0.9)
    ax1.scatter(t_num[flag], los_low_gate_mean[flag], s=16, label="flagged", zorder=3)
    ax1.set_ylabel("LOS velocity (m/s)")
    ax1.set_title(f"Low-gate LOS velocity and flagged anomalous radials (threshold = {LOS_ANOMALY_Z_THRESHOLD:.1f})")
    ax1.legend()
    ax1.grid(alpha=0.3)

    ax2.plot(t_num, score, linewidth=0.9)
    ax2.axhline(LOS_ANOMALY_Z_THRESHOLD, linestyle="--", linewidth=1.0)
    ax2.set_ylabel("Anomaly score")
    ax2.set_xlabel("Local time (UTC+8)")
    ax2.grid(alpha=0.3)

    ax2.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    plt.xticks(rotation=30)
    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    plt.close(fig)


# ======================== Main ========================
def main():
    date_dir = Path(PREPROCESSED_DATE_DIR)
    date_key = str(get_date_from_folder_name(date_dir))
    out_dir = Path(OUTPUT_ROOT) / date_dir.name
    out_dir.mkdir(parents=True, exist_ok=True)

    day = collect_one_day(date_dir)
    height_km = day["range_m"] / 1000.0 * np.sin(np.deg2rad(72.0))

    # SNR curtains
    if USE_COMBINED_SNR:
        plot_time_height_field(
            time_local=day["time_local"],
            height_km=height_km,
            field_2d=day["combined_peak_snr_db"],
            out_png=out_dir / f"{date_key}_combined_peak_snr_db_curtain.png",
            title=f"Combined peak-SNR curtain ({date_key}, UTC+8)",
            cbar_label="Peak SNR (dB)",
            vmin=SNR_VMIN_DB,
            vmax=SNR_VMAX_DB,
            cmap_name="plasma",
        )
    else:
        plot_time_height_field(
            time_local=day["time_local"],
            height_km=height_km,
            field_2d=day["p_peak_snr_db"],
            out_png=out_dir / f"{date_key}_p_peak_snr_db_curtain.png",
            title=f"P-channel peak-SNR curtain ({date_key}, UTC+8)",
            cbar_label="Peak SNR (dB)",
            vmin=SNR_VMIN_DB,
            vmax=SNR_VMAX_DB,
            cmap_name="plasma",
        )
        plot_time_height_field(
            time_local=day["time_local"],
            height_km=height_km,
            field_2d=day["s_peak_snr_db"],
            out_png=out_dir / f"{date_key}_s_peak_snr_db_curtain.png",
            title=f"S-channel peak-SNR curtain ({date_key}, UTC+8)",
            cbar_label="Peak SNR (dB)",
            vmin=SNR_VMIN_DB,
            vmax=SNR_VMAX_DB,
            cmap_name="plasma",
        )

    # Gate-valid ratio curtain
    gate_valid_float = day["combined_gate_valid"].astype(np.float64)
    plot_time_height_field(
        time_local=day["time_local"],
        height_km=height_km,
        field_2d=gate_valid_float,
        out_png=out_dir / f"{date_key}_gate_valid_curtain.png",
        title=f"Gate-level QC mask ({date_key}, UTC+8)",
        cbar_label="QC mask (1=valid, 0=invalid)",
        vmin=0.0,
        vmax=1.0,
        cmap_name="Greens",
    )

    # Profile QC timeline
    plot_profile_valid_timeline(
        time_local=day["time_local"],
        profile_valid=day["profile_valid"],
        low_gate_valid_count=day["low_gate_valid_count"],
        out_png=out_dir / f"{date_key}_profile_qc_timeline.png",
    )

    # LOS anomaly
    los_diag = compute_los_radial_anomaly_scores(day)
    plot_los_anomaly_timeline(
        time_local=day["time_local"],
        los_low_gate_mean=los_diag["los_low_gate_mean"],
        score=los_diag["los_anomaly_score"],
        flag=los_diag["los_anomaly_flag"],
        out_png=out_dir / f"{date_key}_los_anomaly_timeline.png",
    )

    # Save diagnostics arrays
    np.savez_compressed(
        out_dir / f"{date_key}_qc_diagnostics.npz",
        range_m=day["range_m"],
        height_km=height_km,
        timestamp_utc_s=day["timestamp_utc_s"],
        time_local_str=day["time_local"].strftime("%Y-%m-%d %H:%M:%S").to_numpy(dtype="U19"),
        azimuth_deg=day["azimuth_deg"],
        p_peak_snr_db=day["p_peak_snr_db"],
        s_peak_snr_db=day["s_peak_snr_db"],
        combined_peak_snr_db=day["combined_peak_snr_db"],
        combined_gate_valid=day["combined_gate_valid"],
        low_gate_valid_count=day["low_gate_valid_count"],
        profile_valid=day["profile_valid"],
        los_velo_aligned=day["los_velo_aligned"],
        los_low_gate_mean=los_diag["los_low_gate_mean"],
        los_residual_low_gate_mean=los_diag["los_residual_low_gate_mean"],
        los_anomaly_score=los_diag["los_anomaly_score"],
        los_anomaly_flag=los_diag["los_anomaly_flag"],
        los_low_gate_count=np.array(LOS_LOW_GATE_COUNT, dtype=np.int32),
        los_anomaly_z_threshold=np.array(LOS_ANOMALY_Z_THRESHOLD, dtype=np.float64),
        source_npz_path=day["source_npz_path"],
        source_h5_path=day["source_h5_path"],
    )

    print("=" * 72)
    print("QC diagnostics finished")
    print(f"Date folder: {date_dir}")
    print(f"Output dir : {out_dir}")
    print(f"Profiles    : {len(day['timestamp_utc_s'])}")
    print(f"Flagged LOS radials: {int(np.sum(los_diag['los_anomaly_flag']))}")
    print("Generated files:")
    for p in sorted(out_dir.glob("*.png")):
        print(f"  {p.name}")
    print("=" * 72)


if __name__ == "__main__":
    main()
